version: '3.4'

services:
  inlog.desafio.backend.webapi:
    image: ${DOCKER_REGISTRY-}inlogdesafiobackendwebapi
    build:
      context: .
      dockerfile: Inlog.Desafio.Backend.WebApi/Dockerfile
    depends_on:
      - database
    ports:
      - "8081:80"
      - "8082:443"
    restart: always
    environment:
      DBHOST: database
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443;http://+:80
    volumes:
     - ~/.aspnet/https:/https:ro

  database:
    image: postgres:15.3
    container_name: InLogDB_Postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - db-volume:/var/lib/postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: InL0g@1
      POSTGRES_DB: InLogDB

volumes:
  db-volume:  
